$ANSIBLE_VAULT;1.1;AES256
38313961636230346132626665356632333838383637663337356462393436303834623661356638
6632343063623136663534353132386362663163666639350a326366363362313338326133613035
65373466373631333564366435656163393961653338656636363264373239663931653263323361
3934393361363263350a306666653939326636363964393266366336663963623138336131613434
38616333313531383835623737383963346332383464643835363831613831336436663833303664
66663838663764636664363564363533363935363432306339323734646532646635646635326435
62313132663138653061633737376661356564363661373135353166663633626434623534636631
34656434666334363031316136373632373939643732396434623432623335646231396162333231
39396137643234643865366134633039343635396562613830613738366131643538643438383562
37616534336335616464336539383633306234663335383365313736306363333463663737613335
356162316136306534663732393237396430
