---
# tasks file for roles/nginx
- name: Create required log directory
  ansible.builtin.file:
    path: /var/log/myapp
    state: directory
    owner: www-data
    group: adm
    mode: '0755'

- name: Ensure Nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx site configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx


- name: Deploy our site configuration from template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_server_name }}" 
    owner: root
    group: root
    mode: '0644'
  notify: Reload Nginx

- name: Enable our site by creating a symbolic link
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nginx_server_name }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx_server_name }}" 
    state: link
    owner: root
  notify: Reload Nginx

- name: Allow traffic on configured Nginx port
  community.general.ufw:
    rule: allow
    port: "{{ nginx_port }}" 
    proto: tcp
  when: ansible_os_family == "Debian"